name: Create pull request to another repo
on:
  repository_dispatch:
    types: [create-pull-request]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          source-directory: 'source'
          source_folder: 'source'
          destination-github-username: 'sychevsky'
          destination-repository-name: 'ychevsky/infra-repo'
          user-email: carles3@pina.cat
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main

 
