name: Create pull request to another repo
inputs:
  cpu:
    description: 'cpu units'
    required: false
    default: '256'
  ram:
    description: 'ram units'
    required: false
    default: '256'
  name:
    description: 'bot-name'
    required: true
on:
  repository_dispatch:
    types: [create-pull-request]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'source'
        destination_repo: 'sychevsky/infra-repo'
        destination_folder: 'bot'
        destination_base_branch: 'main'
        destination_head_branch: 'add-bot'
        user_email: 'user-name@paygo.com.br'
        user_name: 'sychevsky'
