name: Create pull request to another repo
on:
  repository_dispatch:
    types: [create-pull-request]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          source_folder: 'source'
          destination_repo: 'sychevsky/infra-repo'
          destination_folder: 'bot'
          destination_head_branch: 'add-bot'
          destination_base_branch: 'main'
          user-email: carles3@pina.cat
          user_name: 'bot'
          pull_request_reviewers: 'sychevsky'
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
