name: Create pull request to another repo
on:
  repository_dispatch:
    types: [create-pull-request]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_folder: 'source'
        destination_repo: 'sychevsky/infra-repo'
        destination_folder: 'bot'
        destination_base_branch: 'add-bot'
        destination_head_branch: 'add-bot'
        user_email: 'dmytrosychevsky@gmail.com'
        user_name: 'sychevsky'
